# Generated by Django 3.2.15 on 2022-10-20 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=255)),
                ('year_level', models.PositiveSmallIntegerField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=65535)),
                ('level', models.PositiveSmallIntegerField()),
                ('additional_resource', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('feedback', models.CharField(max_length=65535)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('questions', models.JSONField()),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='instructor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=65535)),
                ('is_correct', models.BooleanField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.question')),
            ],
        ),
        migrations.CreateModel(
            name='SessionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='session', to=settings.AUTH_USER_MODEL)),
                ('student_ids', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student_ids', 'session_id')},
            },
        ),
        migrations.CreateModel(
            name='ClassRoomStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_room_ids', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.classroom')),
                ('student_ids', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student_ids', 'class_room_ids')},
            },
        ),
    ]
