# Generated by Django 3.2.15 on 2022-10-21 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20221021_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionprogress',
            name='attended',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionprogress',
            name='progress',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
