name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        /home/github-runner/.local/bin/poetry install
    - name: Run Tests
      run: |
        python manage.py test
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Deploy
      run: |
        screen -XS backend exit
        screen -dmS backend poetry run python manage.py runserver
