name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        /home/github-runner/.local/bin/poetry export -f requirements.txt --output requirements.txt
        pip install --no-cache-dir -r requirements.txt
    - name: Run Migrate
      run:
        python manage.py migrate
    - name: Run Tests
      run: |
        python manage.py test
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Set path
      run:
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Deploy
      env:
        BASE_URL: 'api/'
        SB_SECRET_KEY: 'django-super-insecure-jl0&pk%5+qlgj@tn#b7)t=zpkbu2lb3#ym(vwkiyx%h$%-5gup'
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        PYTHON_ENV: 'development'
      run: |
        gunicorn strayballoon.wsgi:application --name backend --daemon
