name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        /home/github-runner/.local/bin/poetry export -f requirements.txt --output requirements.txt
        pip install --no-cache-dir -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Deploy
      run: |
        screen -XS backend exit | true
        screen -dmS backend
        screen -XS backend bash -c 'python manage.py runserver'
